### ISSUE TITLE
Add Easter egg

### ISSUE THREAD

**Issue by GUIpsp** [Forkk/MultiMC#15]
There seems to be a lack of Easter eggs
This needs to be fixed ASAP.

**Comment by Forkk** [comment]
<img src="http://kidculture.files.wordpress.com/2011/04/easter-egg.jpg">

**Comment by GUIpsp** [comment]
This Easter egg does not fit the current standard in Easter eggs.

**Comment by Forkk** [comment]
ALL the Easter eggs
<img src="http://oasis-church-nj.com/wp-content/uploads/2011/04/easter-egg.jpg">

**Comment by GUIpsp** [comment]
What year is this? 2011?
Those Easter eggs are as old as my great grand mother.
