### ISSUE TITLE
Make edit mods menu more user friendly

### ISSUE THREAD

**Issue by Forkk** [Forkk/MultiMC#25]
Currently the edit mods menu isn't very intuitive. Users are used to editable lists having buttons for adding items, removing items, and moving items up and down in the list. Adding buttons like this would hopefully make the edit mods dialog more user-friendly.

The list would look something like this:
![Example](http://doc.qt.nokia.com/qq/qq11-stringlistedit.png)

**Comment by finalsliver** [comment]
if you can can you use a graphic representation of up and down? arrows or something. and 2 options;

-Move to first/top

-move to last/bottom

**Comment by Forkk** [comment]
Although I like the idea of move to top / bottom, having that many buttons may clutter the button panel.
