### ISSUE TITLE
Unhandled error when dragging ModLoader and AudioMod in \instances\*\instMods

### ISSUE THREAD

**Issue by tyrope** [Forkk/MultiMC#27]
I tried to drag ModLoader.zip and AudioMod.zip into C:\Users\Tyrope\AppData\Roaming\MultiMC\instances\MC_1.2.5_modded\instMods and got the following [result](http://img210.imageshack.us/img210/4697/multimc.png)

p.s. to ensure I get an email notification, @ mention me in the reply.

Oops, almost forgot to paste the [error report](http://pastebin.com/3pzWRqyC)!

**Comment by Forkk** [comment]
@tyrope this is a bug in 2.3 and is irrelevant to 3.0. Please update to 3.0.

**Comment by tyrope** [comment]
Thanks, @Forkk, but after the update, this bug still lives. [screenshot](http://img831.imageshack.us/img831/4697/multimc.png)

p.s. to ensure I get an email notification, @ mention me in the reply.

edit: turns out after the crash it still installed properly, could this be because I backed up my instances folder and dragged it in without actually launching it through MultiMC?

**Comment by Forkk** [comment]
@tyrope Not sure, could you re-paste the error message? The original one is broken.

**Comment by tyrope** [comment]
It has expired and the original .txt file sadly got deleted during the update (I removed the whole folder to ensure no bugs appear that way.).

After some testing it seems to only happen when I drag it from D:\Downloads and not from my Desktop (which is on the C drive). Perhaps it's because it's loading from different hard drives? Sadly these crashes did **not** produce a bug report!

p.s. to ensure I get an email notification, @ mention me in the reply.

**Comment by finalsliver** [comment]
@tyrope 

Move the MultiMC folder into your Documents and try it their. It sounds like it could be some weird permission problem.

couldn't hurt to try right?

also on the note of different drive's have you hard-linked the downloads folder, or have you manually re-directed your downloads?

I ask as I have hard-linked it to my D: and its working fine.

**Comment by tyrope** [comment]
@finalsliver It can't be a permission problem, I'm the only user of this machine and run everything with elevated access by default.

the drives are a RAID0 of 2 drives, partitioned into seperate areas, so hardlink.

**Comment by Forkk** [comment]
@tyrope If you don't get me an error report I can't help you. Sorry.

**Comment by tyrope** [comment]
@Forkk Make it create an error report and I'll happily provide it, but as mentioned before it doesn't.

**Comment by Forkk** [comment]
@tyrope MultiMC now creates error logs when it crashes (similarly to the way 2.3 did)

**Comment by Forkk** [comment]
This issue appears to be dead now.
