### ISSUE TITLE
MultiMC regularly fails to update due to 'crashed' processes in the background

### ISSUE THREAD

**Issue by lopcode** [Forkk/MultiMC#34]
Hey there,

MultiMC regularly hung before version 3 for me, leaving 'zombie processes' in the background that had to be killed manually.

This meant that the new update was pulled down, but the updater crashed when it tried to delete the file (I'm assuming) because the other zombie processes still had it locked.

Is there a way for MultiMC to kill all of it's own processes forcefully so an update would happen properly?

**Comment by Forkk** [comment]
There may be a way to do this but it likely requires UAC elevation which would require spawning a new process. In addition it probably wouldn't be very platform-independent either.

**Comment by lopcode** [comment]
Failing MultiMC killing the zombie processes, might there be a way to detect if they exist and warn the user to kill the processes then try again, or do a manual update (instead of the updater crashing)?
