### ISSUE TITLE
Audio mod acting odd

### ISSUE THREAD

**Issue by finalsliver** [Forkk/MultiMC#35]
Audio mod has been reported to work for some installs, but not for all. 

some mod sounds are not being played ingame.

Affected

EE

Mo' Creatures

etc

**Comment by Forkk** [comment]
I'll have a look.

**Comment by finalsliver** [comment]
thanks

**Comment by finalsliver** [comment]
thanks for the fix, only noticed what you did then Zombe's modpack complained and gave the directory path XD
