### ISSUE TITLE
Allow launching instances via command line arguments

### ISSUE THREAD

**Issue by finalsliver** [Forkk/MultiMC#41]
Suggestion by Sammko on the forum

---

This is an AMAZING app Thanks alot Forkk. 

Also have you thought about Command Line Argument parsing? like if i do:

"MultiMC.exe -Instance n" 
## it would launch Instance with index n (zero based) cause that would be pretty amazing! and it is not even hard to do in .NET 

seems like it might be a good idea.

**Comment by Forkk** [comment]
Good idea, I'll see what I can do.
