### ISSUE TITLE
External Mods Folder

### ISSUE THREAD

**Issue by finalsliver** [Forkk/MultiMC#45]
Currently I have a folder on my desktop with every 1.2.5 mod I've downloaded, whether they are for myself or testing for those on the forum.

I was wondering if it would be possible to have a Central mods repository folder, linked to the 'edit mods' page.

this would allow people to easily access mods they have already used, which could then be used for new instances.

**Comment by Forkk** [comment]
Good idea

**Comment by finalsliver** [comment]
A user has requested this as-well as having the ability to auto-update mods from this folder into an instance. 

I thought I'd should mention it, but to be honest as there is no standard with which all the mods are named it would be more trouble than its worth.

so as an alternative, what of a common name searching function? select the mod already in use and ask it to list mods from the central repository with similar names? this might work to an extent but would give false positives in the form of mods whose name specify things like :
Modloader-version
Forge Version

etc

**Comment by finalsliver** [comment]
Forkk13 also wants this!!!!! XD

**Comment by Forkk** [comment]
Soon, young grasshopper, soon.

**Comment by Forkk** [comment]
Implemented in 3.1.2.0
