### ISSUE TITLE
Error while compressing .jar

### ISSUE THREAD

**Issue by LuzanelL** [Forkk/MultiMC#47]
MultiMC 3.0.2.3 don't compress .jar correctly, rendering the game unplayable
error proceeds as follow:

Instance started with command: C:\Program Files\Java\jre7\bin\java.exe -Xmx1024m -Xms512m -cp "C:\Users\==\Downloads\MC" MultiMCLauncher "C:\Users\==\Downloads\MC\instances\1.2.5.minecraft" "==" 5166874220673410444
Error occurred during initialization of VM
java/lang/ClassNotFoundException: error in opening JAR file <invalid CEN header (bad compression method)> C:\Program Files\Java\jre7\lib\rt.jar
Instance exited with code: 1
Crash detected!

**Comment by Forkk** [comment]
This is an issue with your java installation. Reinstall java.
