### ISSUE TITLE
Sorting Order for mods tab

### ISSUE THREAD

**Issue by finalsliver** [Forkk/MultiMC#54]
what's the chance for mods folder sorting from the tab?

would probably need an enumerator to rename the mod's
"001_buildcraft-client-A-core-3.1.5"
"002_buildcraft-client-B-builders-3.1.5"

this possible?

**Comment by Forkk** [comment]
Probably not. It doesn't make much sense to do this and it's something the mod devs should be handling on their own. (also, putting numbers before the filenames only works on windows)
