### ISSUE TITLE
Folder support for mods tab

### ISSUE THREAD

**Issue by finalsliver** [Forkk/MultiMC#57]
User's of mods like Portal Gun are reporting that they cant drop the folder in the 'mods' tab and are having to access the folder directly.

there are a few mods like this, though I am pulling up blanks as I think of them.

so the ability to place folder based mods in the GUI would be handy

even if the GUI zips it first then unzips it in the folder

**Comment by Forkk** [comment]
It should already support folders. I'll have a look.

**Comment by finalsliver** [comment]
It worked for me on a second attempt,.. not sure what changed. 

got a feeling its about where you click and drag from in the users case...

**Comment by Forkk** [comment]
Dragging anything from within a zip file into MultiMC does not work.

Edit - Come to think of it, I should make it so you can drag things from zip files.
