### ISSUE TITLE
MultiMC 3.1.1 Mac Compatibility

### ISSUE THREAD

**Issue by finalsliver** [Forkk/MultiMC#61]
fengchiu1997 writes in:

---

Is it possible to move the Instance folder out of the MultiMC.app folder? Because the updating doesn't really work yet on osx, so when ever we manually updates, it covers and deletes anything new.

And about the MultiMC console, I tried that option out, and the console appears every time even when its unchecked in the options.

And the new update with more functionality to creating instances, is crashing on macs, when the button is clicked, it crashes.  

---

any Idea's?

**Comment by adrusi** [comment]
I have the same problem. Here are the logs for launching MultiMC and then pressing the create new instance button http://pastebin.com/raw.php?i=YL5QBMkq

**Comment by Forkk** [comment]
I will add an option to change the location of the instance folder.
