### ISSUE TITLE
Updating overwrites instance folder? (Mac)

### ISSUE THREAD

**Issue by finalsliver** [Forkk/MultiMC#62]
a MAC user has been losing instances on each update

---

[quote name='fengchiu1997' timestamp='1334801265' post='14360452']
Is it possible to move the Instance folder out of the MultiMC.app folder? Because the updating doesn't really work yet on osx, so when ever we manually updates, it covers and deletes anything new.

And about the MultiMC console, I tried that option out, and the console appears every time even when its unchecked in the options.

And the new update with more functionality to creating instances, is crashing on macs, when the button is clicked, it crashe

---

Any Idea's?

**Comment by fengchiu1997** [comment]
Hi, I am fengchiu1997 on the mc forums. Here is some extra info:

[quote name='fengchiu1997' timestamp='1334911887' post='14388326']
Macs treat folders that ends with .app as applications, so when the new MultiMC comes out, I download and replace the application. The "instance" folder is located in side the application it's self, so when ever an update comes, I back up the "instance" folder so as to preserve them. By relocating the instance folder, it would save us some work in updating.
[/quote]

**Comment by Forkk** [comment]
See issue #66
