### ISSUE TITLE
Add option to add a EXE to launch

### ISSUE THREAD

**Issue by woutwoot** [Forkk/MultiMC#70]
A good Idea would be to add a option to add a EXE in addition to a minecraft instance.
Like me, I also play on a Tekkit server (modded MC) and you cant import tekkit into the instances.
Now, I have to start the tekkit launcher manually, if you add this option, I could just start that launcher out of multiMC!
And, sorry for bad english xD

**Comment by Forkk** [comment]
I don't support Technic or Tekkit.
